/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

//<editor-fold defaultstate="collapsed" desc="Imports">
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.KeyStroke;
//</editor-fold>

/**
 *
 * @author Feylin
 */
public class About extends JDialog
{
    //<editor-fold defaultstate="collapsed" desc="Klasse Variabler">
    private static About instance = null;
    private String osArch = System.getProperty("os.arch");
    private String osVersion = System.getProperty("os.version");
    private String osName = System.getProperty("os.name");
    private String javaVendor = System.getProperty("java.vendor");
    private String javaVersion = System.getProperty("java.version");
    private String userName = System.getProperty("user.name");
    private String userHome = System.getProperty("user.home");
    //</editor-fold>

    /**
     * Opretter en ny form af About
     */    
    //<editor-fold defaultstate="collapsed" desc="About Constructor">
    public About()
    {
        setModal(true);
        initComponents();
        setLocationRelativeTo(null);
        closeListener();
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/icons/tennis_ball.png")).getImage());
        txtJava.setText(javaVersion +"; " +javaVendor);
        txtSystem.setText(osName +" version " +osVersion +" running on " +osArch);
        txtUserName.setText(userName);
        txtUserHome.setText(userHome);
    }
    //</editor-fold>
    
    /**
     * Metode til at returnere den eneste instans af denne klasse.
     */
    //<editor-fold defaultstate="collapsed" desc="About Singleton getInstance();">
    public static About getInstance()
    {
        if (instance == null)
        {
            instance = new About();
        }
        return instance;
    }
    //</editor-fold>
    
    /**
     * Metode der tilføjer en close listener der gør det muligt at trykke escape
     * for at lukke vinduet når vinduet er i fokus
     */
    //<editor-fold defaultstate="collapsed" desc="Close Listener">
    private void closeListener()
    {
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(
                KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "close");
        getRootPane().getActionMap().put("close", new AbstractAction()
        {
            @Override
            public void actionPerformed(ActionEvent e)
            {
                dispose();
            }
        });
    }
    //</editor-fold>

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        lblJava = new javax.swing.JTextField();
        txtProduct = new javax.swing.JTextField();
        txtVersion = new javax.swing.JTextField();
        jspAbout = new javax.swing.JScrollPane();
        txtAbout = new javax.swing.JTextPane();
        btnClose = new javax.swing.JButton();
        lblEASV = new javax.swing.JLabel();
        txtJava = new javax.swing.JTextField();
        lblSystem = new javax.swing.JTextField();
        txtSystem = new javax.swing.JTextField();
        txtUserName = new javax.swing.JTextField();
        txtUserHome = new javax.swing.JTextField();
        lblUserName = new javax.swing.JTextField();
        lblUserHome = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblJava.setEditable(false);
        lblJava.setBackground(new java.awt.Color(255, 255, 255));
        lblJava.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblJava.setText("Java: ");
        lblJava.setBorder(null);

        txtProduct.setEditable(false);
        txtProduct.setBackground(new java.awt.Color(255, 255, 255));
        txtProduct.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtProduct.setText("Product Version: ");
        txtProduct.setBorder(null);

        txtVersion.setEditable(false);
        txtVersion.setBackground(new java.awt.Color(255, 255, 255));
        txtVersion.setText("Belman Manager 1.0a (Build 091831052013)");
        txtVersion.setBorder(null);

        jspAbout.setBorder(null);

        txtAbout.setEditable(false);
        txtAbout.setBackground(new java.awt.Color(240, 240, 240));
        txtAbout.setText("This program was developed by\nRashid Abdel-Majid, Mak Jakubovic, Daniel Jensen and Klaus Andresen");
        jspAbout.setViewportView(txtAbout);

        btnClose.setText("Close");
        btnClose.setToolTipText("Closes the window");
        btnClose.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCloseActionPerformed(evt);
            }
        });

        lblEASV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Logo.JPG"))); // NOI18N

        txtJava.setEditable(false);
        txtJava.setBackground(new java.awt.Color(255, 255, 255));
        txtJava.setBorder(null);

        lblSystem.setEditable(false);
        lblSystem.setBackground(new java.awt.Color(255, 255, 255));
        lblSystem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSystem.setText("System: ");
        lblSystem.setBorder(null);

        txtSystem.setEditable(false);
        txtSystem.setBackground(new java.awt.Color(255, 255, 255));
        txtSystem.setBorder(null);

        txtUserName.setEditable(false);
        txtUserName.setBackground(new java.awt.Color(255, 255, 255));
        txtUserName.setBorder(null);

        txtUserHome.setEditable(false);
        txtUserHome.setBackground(new java.awt.Color(255, 255, 255));
        txtUserHome.setBorder(null);

        lblUserName.setEditable(false);
        lblUserName.setBackground(new java.awt.Color(255, 255, 255));
        lblUserName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblUserName.setText("User Name: ");
        lblUserName.setBorder(null);

        lblUserHome.setEditable(false);
        lblUserHome.setBackground(new java.awt.Color(255, 255, 255));
        lblUserHome.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblUserHome.setText("User Home: ");
        lblUserHome.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblUserHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txtUserHome))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblJava, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txtJava))
                    .addComponent(jspAbout, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txtVersion))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSystem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txtSystem))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txtUserName)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(btnClose))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(lblEASV)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEASV)
                .addGap(18, 18, 18)
                .addComponent(jspAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJava, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJava, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSystem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSystem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUserHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUserHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCloseActionPerformed
    {//GEN-HEADEREND:event_btnCloseActionPerformed
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JScrollPane jspAbout;
    private javax.swing.JLabel lblEASV;
    private javax.swing.JTextField lblJava;
    private javax.swing.JTextField lblSystem;
    private javax.swing.JTextField lblUserHome;
    private javax.swing.JTextField lblUserName;
    private javax.swing.JTextPane txtAbout;
    private javax.swing.JTextField txtJava;
    private javax.swing.JTextField txtProduct;
    private javax.swing.JTextField txtSystem;
    private javax.swing.JTextField txtUserHome;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JTextField txtVersion;
    // End of variables declaration//GEN-END:variables
}
